CREATE DATABASE IF NOT EXISTS sso_auth;
USE sso_auth;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255),
  email VARCHAR(255) UNIQUE,
  google_id VARCHAR(255) UNIQUE
);
